color: null
fieldLayouts:
  9d2f83c9-6806-4fab-be52-d81ec9c46b18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-20T06:24:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c80aad79-7db0-44d6-834a-f47a0384086e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-20T06:30:01+00:00'
            elementCondition: null
            fieldUid: 137cb3cd-d6cf-457f-86f9-99e97eaae803 # Cards
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03835d7e-f37a-441f-a405-ba8f736f30d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a80bbc9d-b35b-403d-91e7-03fd0de388ed
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-20T06:48:44+00:00'
            elementCondition: null
            fieldUid: 731cc91d-5ec7-402d-8517-f00dcfd831d6 # Block Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7edb65d-f822-41ce-b2f7-14f3a654357d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-20T14:18:39+00:00'
            elementCondition: null
            fieldUid: ec36a8dc-dd67-4bbc-a01b-065af49e16d4 # Cards Per Row
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 769ced7e-f606-4eeb-8f23-bbbe4db468d2
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: b9e966f7-6b61-4c4a-bbf9-9d83ead1ecb6
        userCondition: null
handle: cards
hasTitleField: false
icon: id-card
name: Cards
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
