color: null
fieldLayouts:
  d678cf4a-c73f-4699-b46d-02a52dde144d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-20T07:49:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b5b8a800-5b67-4e32-9c0f-2ceab097c44b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-20T07:51:17+00:00'
            elementCondition: null
            fieldUid: f058efdf-af3b-4948-9dd7-914ea547cce8 # Entry with URL
            handle: entry
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7afb74d5-93df-4795-8bdd-676b2ce46603
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 8f61e370-5428-43b8-88a2-330c8a996d5c
        userCondition: null
handle: entryCard
hasTitleField: false
icon: newspaper
name: 'Entry Card'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
