color: null
fieldLayouts:
  b1f31252-5743-4d6f-8058-9ceef8a777ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-20T06:26:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb07ca66-247f-4097-a655-8b9b9d116d46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-20T07:01:16+00:00'
            elementCondition: null
            fieldUid: abb455ba-032b-461d-9c8d-dca9ed3fc7bd # Image
            handle: null
            includeInCards: false
            instructions: ' '
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9826c273-8c11-499e-ba8f-1760564ed521
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-20T07:01:16+00:00'
            elementCondition: null
            fieldUid: f232290f-f45b-4537-95e4-353f7e6f6301 # Web Page Url
            handle: externalUrl
            includeInCards: false
            instructions: null
            label: 'External Url'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb261b31-bed1-4163-b366-4a75786db0c1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-20T07:02:48+00:00'
            elementCondition: null
            fieldUid: f37b0bab-9cb9-4695-b431-f05d5e3bd8da # Single Line Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2842d127-1779-421b-9bcf-e711fbd32423
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-20T07:02:48+00:00'
            elementCondition: null
            fieldUid: f37b0bab-9cb9-4695-b431-f05d5e3bd8da # Single Line Text
            handle: subheading
            includeInCards: false
            instructions: null
            label: Subheading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2231d84-26f5-4ace-9640-af7d2c33a631
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 70808d9a-3fda-40da-9e3e-2e32a5dbb812
        userCondition: null
handle: manualCard
hasTitleField: false
icon: credit-card-front
name: 'Manual Card'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
