color: null
fieldLayouts:
  0a8eb920-774e-4467-b009-325d6a5b47a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c79a815d-fcf3-4b68-ba88-5dc03342397b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86b9888e-ef59-4f68-8ece-9b7badf30277 # Multiline Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4fa8163-564d-4a5f-bdf3-92c501282fad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f37b0bab-9cb9-4695-b431-f05d5e3bd8da # Single Line Text
            handle: cite
            includeInCards: false
            instructions: null
            label: Cite
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57d602e9-ba50-41dd-a31b-634f9a7872b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 756bc6cb-dc8c-4411-a1ce-c980d292105f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: eb230d0c-f88a-40de-a743-994de14eb8f8 # Style
            handle: null
            includeInCards: false
            instructions: null
            label: Style
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 867dfbcf-588a-435f-8dbd-b31e4d4a9347
            userCondition: null
            warning: null
            width: 25
        name: Style
        uid: 041dd0f5-7771-4f70-bef2-b7d262683df7
        userCondition: null
handle: quote
hasTitleField: false
icon: quote-right
name: Quote
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
