altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c621664b-f3d6-485e-88c6-102bfda3c7df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-20T19:11:39+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3e49d163-09af-40bd-a7a1-b40f9fbe706f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7029143d-10ca-428f-9a2f-3a17b6d0b273
        userCondition: null
fs: volumesFs
handle: cpFiles
name: 'CP Files'
sortOrder: 3
subpath: cpfiles
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transformFs
transformSubpath: cpfiles
