columnSuffix: null
handle: bgColorWidth
instructions: null
name: 'Background Color Width'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Content width'
        -
          - value
          - default
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Full Width'
        -
          - value
          - full
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
