columnSuffix: null
handle: blockWidth
instructions: null
name: 'Block Width'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - value
          - default
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Wide
        -
          - value
          - wide
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Wider
        -
          - value
          - wider
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Full
        -
          - value
          - full
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
