columnSuffix: null
handle: captionTag
instructions: 'HTML tag to use for the caption.'
name: 'Caption Tag'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - DIV
        -
          - value
          - div
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - H2
        -
          - value
          - h2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H3
        -
          - value
          - h3
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
