columnSuffix: null
handle: cardsPerRow
instructions: 'For large screens, will be restricted for smaller screens.'
name: 'Cards Per Row'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '1'
        -
          - value
          - '1'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '5'
        -
          - value
          - '5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '6'
        -
          - value
          - '6'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
