columnSuffix: null
handle: cardSource
instructions: null
name: 'Card Source'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Create Card From Entry'
        -
          - value
          - createCardFromEntry
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Create Card Manually'
        -
          - value
          - createCardManually
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
