columnSuffix: null
handle: columnSpan
instructions: null
name: 'Column Span'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Half / Half'
        -
          - value
          - '6'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'One Third / Two Thirds'
        -
          - value
          - '4'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Two Thirds / One Third'
        -
          - value
          - '8'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
