columnSuffix: xiqfbbjz
handle: headingLevel
instructions: null
name: 'Heading Level'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - H2
        -
          - value
          - h2
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - H3
        -
          - value
          - h3
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
