columnSuffix: null
handle: toggle
instructions: null
name: Toggle
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
