#!/bin/bash

if [ -z $1 ]
then
    echo Project name missing
    exit 1
fi

echo Installing project $1...

cp .env.example .env &&
ddev config --project-name=$1 &&
ddev start &&
ddev composer install &&
ddev craft db/restore setup/seed.sql.zip --interactive=0 &&
ddev craft setup/keys &&
echo Installing npm packages... &&
ddev npm install &&
ddev npm run build &&
ddev describe &&
ddev launch



