defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8937bb02-c9d0-460b-81ef-1f1bda00e1f7 # Site Info - Global Settings
handle: siteInfo
maxAuthors: 1
name: 'Site Info - Global Settings'
propagationMethod: all
siteSettings:
  2393c71c-94e8-4e90-bb19-949696b8be0b: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  b7acd2cf-9449-4637-a40c-2e266a19cc19: # Deutsch
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
