defaultPlacement: end
enableVersioning: true
entryTypes:
  - fcf21393-86a6-4f40-8a9a-3c829a2316a1 # Topic
handle: topic
maxAuthors: 1
name: Topic
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2393c71c-94e8-4e90-bb19-949696b8be0b: # English
    enabledByDefault: true
    hasUrls: true
    template: _entries/topic
    uriFormat: 'topics/{slug}'
  b7acd2cf-9449-4637-a40c-2e266a19cc19: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _entries/topic
    uriFormat: 'themen/{slug}'
structure:
  maxLevels: 2
  uid: b1c084cd-ea86-49b5-a389-fd8dc76c9281
type: structure
